name: CI Pipeline
on: [push]
jobs:
  test:
    name: Test on Node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10, 12]
        os: [ubuntu-18.04, ubuntu-18.04, ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}

    - name: Install yarn
      run: npm install --global yarn

    - name: Install Dependencies
      run: yarn install --emoji

    - name: Test
      run: yarn test
