name: CI Pipeline
on: [push]
jobs:
  test:
    name: Node v${{ matrix.node_version }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['10.16.3']
        os: [ubuntu-18.04, macOS-10.14, ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Install yarn
      run: npm install --global yarn@^1.17.3

    - name: Install Dependencies
      run: yarn install --emoji

    - name: Test
      run: yarn test
